version: '2.4' 
services:
  mongo:
    image: mongo:3.4
    networks:
      - unifi
    restart: unless-stopped
    volumes:
      - db:/data/db
  controller:
    image: "jacobalberty/unifi:latest"
    depends_on:
      - mongo
    init: true
    networks:
      - unifi
    restart: unless-stopped
    volumes:
      - data:/unifi/data
      - log:/unifi/log
      - cert:/unifi/cert
      - init:/unifi/init.d
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
      TZ: America/Denver #Change for applicable TZ
    ports:
     - '3478:3478/udp'
     - '10001:10001/udp'
     - '6789:6789/tcp'
     - '8080:8080/tcp'
     - '8880:8880/tcp'
     - '8443:8443/tcp'
     - '8843:8843/tcp'
     - '1900:1900/udp'
     - '5656-5699:5656-5699/udp'
  logs:
    image: bash
    depends_on:
      - controller
    command: bash -c 'tail -f /unifi/log/*'
    restart: always
    volumes:
      - log:/unifi/log

volumes:
  db:
  data:
  log:
  cert:
  init:

networks:
  unifi:
